apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    #- ReadOnlyMany  複数ノードからREAD ONLY1マウント可能にするモード
    #- ReadWriteOnce 1つのノードからR/Wでマウントできるモード
  # PersistentVolumeClaim を削除した時の動作
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
  ## マウント先のNFS Serverの情報を記載
  nfs:
    path: /share
    server: 192.168.99.1
