version: 2.1
jobs:
  build:
    working_directory: ~/mydir
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Exec Build
          command: |
            export DOCKER_BUILDKIT=1
            docker version
            make
      - run:
          name: Show Images
          command: |
            docker image ls

workflows:
  version: 2
  build:
    jobs:
      - build
