version: 2.1
jobs:
  build:
    working_directory: ~/mydir
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Exec Build
          command: make

workflows:
  version: 2
  build:
    jobs:
      - build
