version: 2.1

executors:
  linux-os:
    machine:
      enabled: true
    # docker_layer_caching: true
      image: ubuntu-1604:201903-01
  docker-image:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers

jobs:
  build:
    working_directory: ~/mydir
    parallelism: 1
    executor: linux-os
    steps:
      - checkout
      - run:
          name: Show Variable
          command: |
            echo ${FLASK_TOKEN}
            time bash install.sh
            make version
      - run:
          name: run lint
          command: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v1.17.2/hadolint-Linux-x86_64 -o hadolint
            chmod 755 hadolint
            find . -type f -name "Dockerfile" | xargs -L 1 -t ./hadolint || echo ""
      - run:
          name: run Build
          command: |
            export DOCKER_BUILDKIT=1
            docker version
            make
      - run:
          name: Show Images
          command: |
            docker image ls
            df -h

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - deploy
                - beta
          context: flask-context

