version: 2.1
jobs:
  build:
    working_directory: ~/mydir
    machine:
      enabled: true
      # docker_layer_caching: true
      # image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Show Variable
          command: |
            time bash install.sh
      - run:
          name: run lint
          command: |
            curl -L https://github.com/hadolint/hadolint/releases/download/v1.17.2/hadolint-Linux-x86_64 -o hadolint
            chmod 755 hadolint
            find . -type f -name "Dockerfile" | xargs -L 1 -t ./hadolint || echo ""
      - run:
          name: run Build
          command: |
            export DOCKER_BUILDKIT=1
            docker version
            make
      - run:
          name: Show Images
          command: |
            docker image ls
            df -h
      - run:
          name: run Container
          command: docker image ls | awk '{print $1":"$2}' | grep -v "<none>" | xargs -L 1 docker run -d

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - deploy
                - beta

