version: '3'

services: 
  db:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: root # スーパーユーザのパスワード
    tty: true
    stdin_open: true
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
