version: '3'

services:
  web:
    image: nginx
    container_name: nginx
    tty: true
    stdin_open: true
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    ports:
      - "8080:80"
